language: cpp
dist: bionic
compiler: gcc

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default
  # Wt
  - sudo apt-get install witty witty-dbg witty-dev witty-doc
  # Codecov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint

services:
 - xvfb

script: 
  - ./download_other_githubs
  # Console
  - qmake -qt=qt5 RandomCodeConsole.pro
  - make debug
  - ./RandomCodeConsole
  # Desktop
  - qmake -qt=qt5 RandomCodeDesktop.pro
  - make debug
  - ./RandomCodeDesktop &
  - sleep 10
  - sudo killall RandomCodeDesktop
  # Website
  - qmake -qt=qt5 RandomCodeWebsite.pro
  - make debug
  - ./RandomCodeWebsite &
  - sleep 10
  - sudo killall RandomCodeWebsite
  # Get code coverage
  - ./get_code_cov
  - codecov
  # Call OCLint
  - ./do_oclint

after_success:
  - bash <(curl -s https://codecov.io/bash)